- name: List target IPs and confirm
  debug:
    msg: "Target IP"

- pause:
    prompt: "Do you wish to proceed? (yes/no)"
  register: var_proceed

- meta: end_play
  when: var_proceed.user_input == "no"

