- name: List target IPs and confirm
  debug:
    msg: "Target IP"

- pause:
    prompt: 'Do you wish to proceed? ("yes" to proceed/any other input to abort)'
  register: var_proceed

- meta: end_play
  when: var_proceed.user_input != "yes"

