- name: "Setup ssh"
  set_fact:
    ansible_user: "{{ssh_user}}"
    ansible_ssh_private_key_file: "{{ssh_pem}}"

#- debug:
#    msg: "{{ssh_target}} : {{ansible_user}} : {{ansible_ssh_private_key_file}}"

- name: Get ownership before update
  stat:
    path: /etc/sensu/conf.d/client.json
  register: st_before

- name: Actual attempt to change the threshold values
  ghetto_json:
    path=/etc/sensu/conf.d/client.json
    client.keepalive.thresholds.warning={{sensu_threshold_warning}}
    client.keepalive.thresholds.critical={{sensu_threshold_critical}}

- name: Get ownership after update
  stat:
    path: /etc/sensu/conf.d/client.json
  register: st_after

- name: Check if file ownership has changed
  fail:
    msg: "Yikes, file ownership has changed!"
  when: st_before.stat.pw_name != st_after.stat.pw_name

- name: Restart sensu
  command: echo "Restarting sensu services"
  notify: "restart sensu services"
