---
cloud_target: aws gcp

aws_region_target: us-east-1 us-east-2 us-west-2 ap-southeast-1 ap-southeast-2 eu-west-1 ca-central-1
aws_profile: production
aws_ssh_pem: ~/.pems/key-aws-maas-prod.pem
aws_ssh_user: ubuntu

gcp_region_target: us-central1 europe-west1
gcp_profile: ~/.pems/maas-gcp-orchestrator-prod.json
gcp_ssh_pem: ~/.pems/maas-gcp-orchestrator-prod.pem
gcp_ssh_user: ubuntu

sensu_threshold_warning: 90
sensu_threshold_critical: 120
