- name: EC2 instances
  hosts: 54.179.181.16
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.pems/key-aws-maas-staging.pem
  tasks:
    - name: Get owner before change
      stat:
        path: /etc/sensu/conf.d/client.json
      register: st_before

    - name: Get owner after change
      stat:
        path: /etc/sensu/conf.d/client.json
      register: st_after
        
    - name: Check if ownership changed
      fail:
        msg: "Yikes, file ownership has changed!"
      when: st_before.stat.pw_name == st_after.stat.pw_name

