- name: Extract target IPs
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Clear inventory
    block:
      - find:
          paths: ./inventory 
          patterns: "*"
        register: files_to_delete

      - file:
          path: "{{ item.path }}"
          state: absent
        with_items: "{{ files_to_delete.files }}"    
  
  - name: Generate AWS inventory
    shell: "{{ item }}"
    with_items:
      - echo "[aws]" >> ./inventory/aws
      - maas-cli aws all -p staging | grep -E 'EC2PrimaryVmr|EC2BackupVmr|EC2MonitoringVmr' | cut -d"|" -f3 >> ./inventory/aws 

  - name: Generate GCP inventory
    shell: "{{ item }}"
    with_items:
      - echo "[gcp]" >> ./inventory/gcp
      - maas-cli gcp all -c ~/.maas/stg-maas-cli.yml -f ~/.pems/maas-gcp-orchestrator-staging.json | grep -E 'svmr' | cut -d"|" -f3 >> ./inventory/gcp 
    
  - name: Refresh inventory
    meta: refresh_inventory

- name: AWS EC2 instances
  hosts: aws
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.pems/key-aws-maas-staging.pem

- name: GCP instances
  hosts: gcp
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.pems/maas-gcp-orchestrator-staging-ssh.pem
